name: Update Files on Complete Setup Issue

permissions:
  contents: write

on:
  issues:
    types: [opened, edited]

jobs:
  update-files:
    runs-on: ubuntu-latest
    if: github.event.issue.title == 'Complete Setup'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Git Config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Display Issue Details (Debug)
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"

      - name: Update Files Based on Issue Input
        run: |
          # Assign the issue body to a variable.
          ISSUE_BODY="${{ github.event.issue.body }}"
          
          # For demonstration, suppose your README.md contains the placeholder: %%CUSTOM_MESSAGE%%
          # We'll replace it with the custom message provided in the issue.
          
          # Extract the custom message from the issue body.
          # Using awk to find the line after '### Custom Message'
          CUSTOM_MESSAGE=$(echo "$ISSUE_BODY" | awk '
              BEGIN { found=0 }
              {
                if (found && $0 ~ /[[:alnum:]]/) { 
                  print; exit 
                }
                if ($0 ~ /###[[:space:]]*Custom Message/) {
                  found=1
                }
              }')
          
          echo "Custom message extracted: $CUSTOM_MESSAGE"
          
          # Replace placeholder in README.md (or any file) with the custom message.
          if [ -n "$CUSTOM_MESSAGE" ]; then
            sed -i "s|%%CUSTOM_MESSAGE%%|$CUSTOM_MESSAGE|g" README.md
          else
            echo "No custom message found, skipping file update."
          fi

      - name: Commit and Push Changes
        run: |
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Updated files based on Complete Setup issue submission"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Close the Issue
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: "closed"
            });
